version: '3.4'

services:
  gateway:
    image: MMLib.Microservices/gateway
    ports:
      - 5000:5000

  users:
    image: MMLib.Microservices/users
    depends_on:
      - storage-seed

  basket:
    image: MMLib.Microservices/basket
    depends_on:
      - redis

  ordering:
    image: MMLib.Microservices/ordering
    depends_on:
      - database

  catalog:
    image: MMLib.Microservices/catalog
    depends_on:
      - database

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: on-failure
    ports:
      - 10001:10001 # blob storage
      - 10002:10002 # table storage

  storage-seed:
    image: krossk/storage-seed
    environment:
      - TABLES=Users
      - HOST_NAME=storage
    depends_on:
      - storage

  database:
    image: krossk/mssql
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=str0ngP@ass
      - MSSQL_PID=Developer
      - DATABASES=Catalog,Orders
    ports:
      - 1434:1433

  redis:
    image: redis
    restart: on-failure