apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway
  template:
    metadata:
      labels:
        app: eshop
        service: gateway
    spec:
      containers:
        - name: gateway
          image: minoregistry.azurecr.io/microservices/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: eshop
    service: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: gateway