CREATE TABLE [dbo].Orders (
    [Id] bigint IDENTITY(1,1) NOT NULL,
    [BuyerId] [int] NOT NULL,
    [Items] [nvarchar](max)
CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO