SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].Products (
    [Id] bigint IDENTITY(1,1) NOT NULL,

    [Name] varchar(255) NOT NULL,
    [Description] varchar(max) NOT NULL DEFAULT (''),
    [Price] decimal(28,3) NOT NULL DEFAULT (0),

    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([Id] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO