CREATE TABLE [dbo].Basket (
    [BuyerId] [int] NOT NULL,
    [Items] [nvarchar](max)
CONSTRAINT [PK_Basket] PRIMARY KEY CLUSTERED ([BuyerId] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO