name: Publish Images to registry

# Controls when the action will run.
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Setup .NET Core if needed
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.300
      
      - name: Setup dotnet (for AZFunctions)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Nuke build docker images
        run: ./build.sh --target Publish+DockerBuild --Configuration Release --verbosity verbose

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          login-server: mmlib.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Nuke push docker images to registry
        run: ./build.sh --target DockerPush --Configuration Release --verbosity verbose