name: Pull Request

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.101

    - name: Set up node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'

    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra

    - name: Nuke integration tests
      run: ./build.sh --target Publish+DockerBuild+ComposeUp+IntegrationTests+DockerRm --Configuration Release --UseRegistry false --verbosity verbose --ServicesTag ${{ github.run_id }}
